/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BaseLevel: typeof import('./src/scenes/BaseLevel')['BaseLevel']
  const BeginningChunk: typeof import('./src/scenes/level-chunks/BeginningChunk')['BeginningChunk']
  const BoundaryWallsChunk: typeof import('./src/scenes/level-chunks/BoundaryWallsChunk')['BoundaryWallsChunk']
  const COLLISION_GROUPS: typeof import('./src/constants/collision-groups')['COLLISION_GROUPS']
  const DIMENSIONS: typeof import('./src/constants/dimensions')['DIMENSIONS']
  const DamagingObstacle: typeof import('./src/entities/DamagingObstacles')['DamagingObstacle']
  const Gem: typeof import('./src/entities/Gem')['Gem']
  const Hook: typeof import('./src/systems/hook-system/hook')['Hook']
  const HookIndicator: typeof import('./src/systems/hook-system/indicator')['HookIndicator']
  const HookSystem: typeof import('./src/systems/hook-system/hook-system')['HookSystem']
  const InGameUI: typeof import('./src/ui/InGameUI')['InGameUI']
  const Level1: typeof import('./src/scenes/levels/Level1')['Level1']
  const Level2: typeof import('./src/scenes/levels/Level2')['Level2']
  const Level3: typeof import('./src/scenes/levels/Level3')['Level3']
  const LevelDesignChunk: typeof import('./src/scenes/level-chunks/LevelDesignChunk')['LevelDesignChunk']
  const LevelMap: typeof import('./src/ui/LevelMap')['LevelMap']
  const MainScene: typeof import('./src/scenes/MainScene')['default']
  const Obstacle: typeof import('./src/entities/Obstacle')['Obstacle']
  const Phaser: typeof import('phaser')['default']
  const Player: typeof import('./src/entities/Player')['Player']
  const PlayerGemCountUI: typeof import('./src/ui/PlayerGemCountUI')['PlayerGemCountUI']
  const PlayerLifeUI: typeof import('./src/ui/PlayerLifeUI')['PlayerLifeUI']
  const Princess: typeof import('./src/entities/Princess')['Princess']
  const PrincessIndicator: typeof import('./src/ui/PrincessIndicator')['PrincessIndicator']
  const ProjectileSystem: typeof import('./src/systems/projectile-system/projectile-system')['ProjectileSystem']
  const SPRITESHEET_FRAMES: typeof import('./src/constants/spritesheet-frames')['SPRITESHEET_FRAMES']
  const SceneEnvironment: typeof import('./src/entities/SceneEnvironment')['default']
  const SpriteFont: typeof import('./src/ui/SpriteFont')['SpriteFont']
  const SpriteFontHelper: typeof import('./src/utils/sprite-font-helper')['SpriteFontHelper']
  const TesetScene: typeof import('./src/scenes/TesetScene')['default']
  const TestScene: typeof import('./src/scenes/TestScene')['default']
  const TitleScene: typeof import('./src/scenes/TitleScene')['default']
  const TransitionScene: typeof import('./src/scenes/TransitionSecene')['TransitionScene']
  const WallJumpChunk: typeof import('./src/scenes/level-chunks/WallJumpChunk')['WallJumpChunk']
  const WallRunningEffects: typeof import('./src/systems/wall-running/wall-running-effects')['WallRunningEffects']
  const WallRunningSystem: typeof import('./src/systems/wall-running/wall-running')['WallRunningSystem']
  const colors: typeof import('./src/utils/colors')['colors']
  const createBeginningChunk: typeof import('./src/scenes/level-chunks/BeginningChunk')['createBeginningChunk']
  const createBoundaryWallsChunk: typeof import('./src/scenes/level-chunks/BoundaryWallsChunk')['createBoundaryWallsChunk']
  const createDamagingObstacleElement: typeof import('./src/factories/level-design-element-factory')['createDamagingObstacleElement']
  const createGemElement: typeof import('./src/factories/level-design-element-factory')['createGemElement']
  const createObstacleElement: typeof import('./src/factories/level-design-element-factory')['createObstacleElement']
  const createObstacles: typeof import('./src/factories/obstacle-factory')['createObstacles']
  const createStaticObstacles: typeof import('./src/factories/obstacle-factory')['createStaticObstacles']
  const createWallJumpChunk: typeof import('./src/scenes/level-chunks/WallJumpChunk')['createWallJumpChunk']
  const createWallObstacleElement: typeof import('./src/factories/level-design-element-factory')['createWallObstacleElement']
  const default: typeof import('phaser')['default']
  const getClosestPointToSource: typeof import('./src/utils/obstacle')['getClosestPointToSource']
  const getClosestPointToSourceWithAngle: typeof import('./src/utils/obstacle')['getClosestPointToSourceWithAngle']
  const getColisionSide: typeof import('./src/utils/collision')['getColisionSide']
  const getCollisionWithPlayer: typeof import('./src/utils/collision')['getCollisionWithPlayer']
  const getDangerousObstacles: typeof import('./src/utils/obstacle')['getDangerousObstacles']
  const getPlayerFromCollision: typeof import('./src/utils/collision')['getPlayerFromCollision']
  const getRunnableObstacles: typeof import('./src/utils/obstacle')['getRunnableObstacles']
  const logger: typeof import('./src/utils/logger')['logger']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { DamagingObstacle, DamagingObstacleOptions } from './src/entities/DamagingObstacles'
  import('./src/entities/DamagingObstacles')
  // @ts-ignore
  export type { Gem } from './src/entities/Gem'
  import('./src/entities/Gem')
  // @ts-ignore
  export type { Obstacle, ObstacleOptions } from './src/entities/Obstacle'
  import('./src/entities/Obstacle')
  // @ts-ignore
  export type { Player } from './src/entities/Player'
  import('./src/entities/Player')
  // @ts-ignore
  export type { Princess } from './src/entities/Princess'
  import('./src/entities/Princess')
  // @ts-ignore
  export type { BaseLevel, LevelOptions } from './src/scenes/BaseLevel'
  import('./src/scenes/BaseLevel')
  // @ts-ignore
  export type { TransitionScene } from './src/scenes/TransitionSecene'
  import('./src/scenes/TransitionSecene')
  // @ts-ignore
  export type { BeginningChunk } from './src/scenes/level-chunks/BeginningChunk'
  import('./src/scenes/level-chunks/BeginningChunk')
  // @ts-ignore
  export type { BoundaryWallsChunk } from './src/scenes/level-chunks/BoundaryWallsChunk'
  import('./src/scenes/level-chunks/BoundaryWallsChunk')
  // @ts-ignore
  export type { LevelDesignChunk, LevelDesignChunkOptions } from './src/scenes/level-chunks/LevelDesignChunk'
  import('./src/scenes/level-chunks/LevelDesignChunk')
  // @ts-ignore
  export type { WallJumpChunk } from './src/scenes/level-chunks/WallJumpChunk'
  import('./src/scenes/level-chunks/WallJumpChunk')
  // @ts-ignore
  export type { Level1 } from './src/scenes/levels/Level1'
  import('./src/scenes/levels/Level1')
  // @ts-ignore
  export type { Level2 } from './src/scenes/levels/Level2'
  import('./src/scenes/levels/Level2')
  // @ts-ignore
  export type { Level3 } from './src/scenes/levels/Level3'
  import('./src/scenes/levels/Level3')
  // @ts-ignore
  export type { HookSystem } from './src/systems/hook-system/hook-system'
  import('./src/systems/hook-system/hook-system')
  // @ts-ignore
  export type { Hook } from './src/systems/hook-system/hook'
  import('./src/systems/hook-system/hook')
  // @ts-ignore
  export type { HookIndicator } from './src/systems/hook-system/indicator'
  import('./src/systems/hook-system/indicator')
  // @ts-ignore
  export type { ProjectileSystem, ProjectileSystemOptions } from './src/systems/projectile-system/projectile-system'
  import('./src/systems/projectile-system/projectile-system')
  // @ts-ignore
  export type { WallRunningEffects } from './src/systems/wall-running/wall-running-effects'
  import('./src/systems/wall-running/wall-running-effects')
  // @ts-ignore
  export type { WallRunningSystem, WallRunningConfig, WallRunningSystemOptions } from './src/systems/wall-running/wall-running'
  import('./src/systems/wall-running/wall-running')
  // @ts-ignore
  export type { LevelDesignElementWithObstacle, LevelDesignElementWithGem, LevelDesignElementWithDamagingObstacle, LevelDesignElement } from './src/types/LevelDesignElement'
  import('./src/types/LevelDesignElement')
  // @ts-ignore
  export type { InGameUI } from './src/ui/InGameUI'
  import('./src/ui/InGameUI')
  // @ts-ignore
  export type { LevelMap } from './src/ui/LevelMap'
  import('./src/ui/LevelMap')
  // @ts-ignore
  export type { PlayerGemCountUI } from './src/ui/PlayerGemCountUI'
  import('./src/ui/PlayerGemCountUI')
  // @ts-ignore
  export type { PlayerLifeUI } from './src/ui/PlayerLifeUI'
  import('./src/ui/PlayerLifeUI')
  // @ts-ignore
  export type { PrincessIndicator } from './src/ui/PrincessIndicator'
  import('./src/ui/PrincessIndicator')
}
